name: Manually deploy 2
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which env to deploy'
        required: true
        default: 'qa'
      version:
        description: 'Version of artifact'
        required: true
        default: ''

  # workflow_run:
  #   workflows: ["CI build"]
  #   branches: [main]
  #   types:
  #     - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}

    - name: Deploy to dev
      run: |
          echo "Deploy to ${{ github.event.inputs.environment }} with artifact ${{ github.event.inputs.version }}!"
      if: ${{ github.event.inputs.environment == 'dev' }} || ${{ github.workflow.name == 'CI build' }}

    - name: Deploy to qa
      run: |
          echo "Deploy to ${{ github.event.inputs.environment }} with artifact ${{ github.event.inputs.version }}!"
      if: ${{ github.event.inputs.environment == 'qa' }}

    - name: Deploy to stg
      run: |
        echo "Deploy to ${{ github.event.inputs.environment }} with artifact ${{ github.event.inputs.version }}!"
      if: ${{ github.event.inputs.environment == 'stg' }}

    # - uses: notlmn/release-with-changelog@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     exclude: '^Meta'
    #     commit-template: '- {title} ← {hash}'
    #     template: |
    #       ### Changelog

    #       {commits}

    #       {range}

    #       ❤
