name: Manually deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which env to deploy'
        required: true
        default: 'qa'
      version:
        description: 'Version of artifact'
        required: true
        default: ''

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to dev
      run: |
          echo "Deploy to ${{ github.event.inputs.environment }} with artifact ${{ github.event.inputs.version }}!"
      if: ${{ github.event.inputs.environment == 'dev' }}

  deploy_to_qa:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to qa
      run: |
          echo "Deploy to ${{ github.event.inputs.environment }} with artifact ${{ github.event.inputs.version }}!"
      # if: ${{ github.event.inputs.environment == 'qa' }}
    - name: Microsoft Teams Notification
      uses: skitionek/notify-microsoft-teams@master
      if: always()
      with:
        webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}

  deploy_to_stg:
    runs-on: ubuntu-latest
    environment:
      name: stg
      url: https://test.net
    steps:
    - name: Deploy to stg
      run: |
        echo "Deploy to ${{ github.event.inputs.environment }} with artifact ${{ github.event.inputs.version }}!"
      # if: ${{ github.event.inputs.environment == 'stg' }}

  # if_failure:
  #   name: Only if failure
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Microsoft Teams Notification
  #       uses: skitionek/notify-microsoft-teams@master
  #       if: failure()
  #       with:
  #         webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
