name: Manually deploy 2
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which env to deploy'
        required: true
        default: 'qa'
      version:
        description: 'Version of artifact'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to dev
      run: |
          echo "Deploy to ${{ github.event.inputs.environment }} with artifact ${{ github.event.inputs.version }}!"
      if: ${{ github.event.inputs.environment == 'dev' }}

    - name: Deploy to qa
      run: |
          echo "Deploy to ${{ github.event.inputs.environment }} with artifact ${{ github.event.inputs.version }}!"
      if: ${{ github.event.inputs.environment == 'qa' }}

    - name: Deploy to stg
      run: |
        echo "Deploy to ${{ github.event.inputs.environment }} with artifact ${{ github.event.inputs.version }}!"
      if: ${{ github.event.inputs.environment == 'stg' }}