name: Create Release v2

on:
  push:
    branches:
      - "release-*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Get release version from version.txt
      id: version
      run: echo ::set-output name=version::$(cat version.txt)

    - name: Print release version.txt version
      run: echo "Release Version is ${{ steps.version.outputs.version }}"

    - name: Extract version from branch name (for release branches)
      id: branch_version
      run: |
        BRANCH_VERSION=$(echo ${GITHUB_REF##*/} | cut -d '-' -f2)
        echo "BRANCH_VERSION = $BRANCH_VERSION"
        echo ::set-output name=branch_version::$BRANCH_VERSION

    - name: Debug output BRANCH_VERSION
      run: echo "Branch version ${{ steps.branch_version.outputs.branch_version }}"

    - name: Check if version.txt equal to release version
      run: |
        if [[ $(echo ${{ steps.branch_version.outputs.branch_version }} | tr -d '.') -eq $(echo ${{ steps.version.outputs.version }} | tr -d '.' ]]; then
            echo "Branch version equal to version in version.txt"
            exit 0
        else
            echo "Branch version is different to version in version.txt"
            exit 1
        fi

    - name: Build Code
      run: echo "Build Code"

    - name: Test Code
      run: echo "Build Code"

    - name: Build and Push Docker Image
      run: echo "New docker image"

    - name: Deploy to Stg
      run: echo "Deploy to Stg"

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@latest
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     body: |
    #       Changes in this Release
    #       - First Change
    #       - Second Change
    #     draft: false
    #     prerelease: false

    # - uses: notlmn/release-with-changelog@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     exclude: '^Meta'
    #     commit-template: '- {title} ← {hash}'
    #     template: |
    #       ### Changelog

    #       {commits}

    #       {range}

    #       ❤