on:
  push
    # Sequence of patterns matched against refs/tags
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Get release version
      id: version
      run: echo ::set-output name=version::$(cat version.txt)

    - name: Print release version
      run: echo "Release Version is ${{ steps.version.outputs.version }}"
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@latest
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     body: |
    #       Changes in this Release
    #       - First Change
    #       - Second Change
    #     draft: false
    #     prerelease: false

    # - uses: notlmn/release-with-changelog@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     exclude: '^Meta'
    #     commit-template: '- {title} ← {hash}'
    #     template: |
    #       ### Changelog

    #       {commits}

    #       {range}

    #       ❤
